version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php app.php"
  relay: pipes

temporal:
    address: temporal:7233
    activities:
        num_workers: 3
        #max_jobs: 10
        supervisor:
            idle_ttl: 10s
            max_worker_memory: 128
            exec_ttl: 30s

#  listen: "tcp://localhost:9001"
#  proto:
#    - "first.proto"

metrics:
  address: localhost:2112
